version: "1.0"
info:
  model: int-scaffold
packages:
- name: ElderaProject
  gitServerName: sancGhPers
  gitUrl: https://github.com/chakraborty-sanjib
  gitUsername: chakraborty-sanjib
  gitBranch: main
configurationVariables:
  jdbcfunc.SAPTxStore.failFastMode: false
  jdbcfunc.SAPTxStore.connPoolAlias: SAP TxStore Pool
